In [1]:
import numpy as np
import pandas as pd

In [116]:
data = pd.read_csv('dataset_Facebook.csv', sep=";")

In [138]:
data

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0,2752,5091,178,109,159,3078,1640,119,4,79,17,100
1,139441,Status,2,12,3,10,0,10460,19057,1457,1361,1674,11710,6112,1108,5,130,29,164
2,139441,Photo,3,12,3,3,0,2413,4373,177,113,154,2812,1503,132,0,66,14,80
3,139441,Photo,2,12,2,10,1,50128,87991,2211,790,1119,61027,32048,1386,58,1572,147,1777
4,139441,Photo,2,12,2,3,0,7244,13594,671,410,580,6228,3200,396,19,325,49,393
5,139441,Status,2,12,1,9,0,10472,20849,1191,1073,1389,16034,7852,1016,1,152,33,186
6,139441,Photo,3,12,1,3,1,11692,19479,481,265,364,15432,9328,379,3,249,27,279
7,139441,Photo,3,12,7,9,1,13720,24137,537,232,305,19728,11056,422,0,325,14,339
8,139441,Status,2,12,7,3,0,11844,22538,1530,1407,1692,15220,7912,1250,0,161,31,192
9,139441,Photo,3,12,6,10,0,4694,8668,280,183,250,4309,2324,199,3,113,26,142
10,139441,Status,2,12,5,10,0,21744,42334,4258,4100,4540,37849,18952,3798,0,233,19,252
11,139441,Photo,2,12,5,10,0,3112,5590,208,127,145,3887,2174,165,0,88,18,106
12,139441,Photo,2,12,5,10,0,2847,5133,193,115,133,3779,2072,152,0,90,14,104
13,139441,Photo,2,12,5,3,0,2549,4896,249,134,168,3631,1917,183,5,137,10,152
14,138414,Photo,2,12,4,5,1,22784,39941,887,337,417,34415,19312,684,2,577,20,599
15,138414,Status,2,12,3,10,0,10060,19680,1264,1209,1425,17272,8548,1162,4,86,18,108
16,138414,Photo,3,12,3,3,0,1722,2981,163,123,148,1868,1050,123,2,40,12,54
17,138414,Photo,1,12,2,12,1,53264,111785,1706,1103,1655,92512,39776,1307,15,678,20,713
18,138414,Status,3,12,2,3,0,3930,7509,130,86,112,5009,2410,101,4,54,17,75
19,138414,Photo,3,12,1,11,0,1591,2825,121,88,111,2116,1161,100,0,34,8,42
20,138414,Photo,2,12,1,3,0,2848,5066,200,142,184,3561,1963,157,3,66,12,81
21,138414,Photo,1,12,7,10,0,1384,2467,15,15,20,2196,1172,15,0,0,0,0
22,138414,Link,1,12,7,10,0,3454,6853,118,104,130,6282,3100,106,0,16,2,18
23,138414,Photo,3,12,7,3,0,2723,4888,176,118,143,2964,1621,143,0,72,24,96
24,138414,Status,2,12,6,10,0,8488,15294,1341,1270,1489,9684,5244,995,3,99,19,121
25,138458,Status,2,12,6,3,0,8284,15104,1521,1462,1711,10266,5372,1200,0,88,18,106
26,138458,Status,2,12,5,11,0,19552,34143,2806,2531,3420,17748,9824,1779,10,412,72,494
27,138458,Photo,3,12,5,3,0,2478,4306,212,124,149,2612,1443,166,0,100,17,117
28,138895,Photo,2,12,5,3,0,9560,18264,973,559,885,9217,4748,621,36,523,63,622
29,138895,Video,1,12,4,11,1,36208,61262,1141,1068,1728,30131,14112,559,18,143,13,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,91437,Link,1,2,3,13,0,9356,14986,448,381,505,13919,8460,392,4,114,13,131
471,91330,Photo,3,2,3,3,0,7732,13264,1066,1002,1336,8753,4880,570,7,160,57,224
472,91223,Photo,1,2,2,13,0,5240,8893,857,837,1020,7420,4232,466,0,46,15,61
473,91116,Photo,3,2,2,4,1,7132,12060,1004,944,1226,8294,4736,576,4,136,42,182
474,91009,Photo,1,2,1,12,0,21928,39641,1512,1479,1837,6338,3672,497,0,73,13,86
475,86909,Photo,3,1,6,16,1,5754,9238,1179,1143,1452,6101,3546,420,0,65,19,84
476,86909,Photo,1,1,6,10,1,37088,10966,2728,2288,3183,66311,34352,2021,7,579,47,633
477,86909,Link,1,1,6,4,0,39600,7927,572,496,581,12522,8176,167,1,101,5,107
478,86909,Photo,3,1,5,13,0,5536,8745,1141,1099,1461,5225,3098,483,1,74,31,106
479,86909,Photo,3,1,5,4,0,6056,10325,1117,1078,1427,6823,3788,487,7,84,36,127
480,86909,Photo,2,1,4,11,0,11484,20696,1762,1635,2741,8774,5124,722,56,360,99,515
481,86491,Link,1,1,4,4,1,4938,7910,66,63,70,6625,3804,59,0,5,2,7
482,86491,Photo,3,1,3,10,0,66784,9456,2969,2833,3645,17809,11328,801,3,187,36,226
483,86491,Photo,2,1,3,3,0,5526,8779,1096,1058,1399,5732,3412,453,2,69,26,97
484,86491,Photo,3,1,2,7,0,5040,8367,1062,1023,1348,5485,3068,437,2,82,24,108
485,86491,Link,1,1,2,2,0,5168,8371,66,59,71,7041,3996,58,0,12,2,14
486,85979,Photo,3,1,1,12,0,5034,8030,1020,993,1243,5340,3094,440,2,56,25,83
487,85979,Photo,3,1,1,2,0,4908,7491,957,937,1153,4642,2842,393,1,44,21,66
488,85979,Photo,3,1,7,10,0,9700,17442,1407,1271,2007,8872,4876,660,21,277,80,378
489,85979,Photo,3,1,7,2,0,4800,7754,975,938,1278,4932,2820,432,1,74,28,103
490,85979,Photo,3,1,6,11,0,5280,8703,951,911,1237,5757,3300,431,1,79,30,110
491,85979,Photo,3,1,6,3,1,6184,10228,956,901,1140,6085,3502,437,1,105,46,152
492,85979,Link,1,1,5,11,0,45920,5808,753,655,763,15766,10720,220,0,128,9,137
493,85093,Photo,3,1,1,2,0,8412,13960,1179,1111,1632,8632,5348,699,17,185,55,257
494,85093,Photo,3,1,7,10,0,5400,9218,810,756,1003,5654,3230,422,10,125,41,176
495,85093,Photo,3,1,7,2,0,4684,7536,733,708,985,4750,2876,392,5,53,26,84
496,81370,Photo,2,1,5,8,0,3480,6229,537,508,687,3961,2104,301,0,53,22,75
497,81370,Photo,1,1,5,2,0,3778,7216,625,572,795,4742,2388,363,4,93,18,115
498,81370,Photo,3,1,4,11,0,4156,7564,626,574,832,4534,2452,370,7,91,38,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91,28,119

#### Для начала я находил  значения по столбцам для всего массива.

Для данных в столбоцах Type, Category, Post Month, Post Weekday, Post Hour, Paid я не стал рассчитывать значения, так как они не имеют ценности.

Post Month, Post Weekday, Post Hour - это временные признаки события(фотографии, видео, статуса или ссылки) и, разве что мода может дать нам каку-то информацию, например в какой день недели или месяц чаще публикуются важные события.

Type, Category - категориальные признаки.

Paid - бинарный признак(опять же не имеет смысла расчитывать среднее, макс/мин, медиану).

In [68]:
notValid = ["Type","Category","Post Month","Post Weekday", "Post Hour","Paid"]

In [71]:
for i in data.columns:
    if i not in notValid:
        print(i.upper() ,'\n','Среднее значение:',data[i].mean(), "Максимальное:", data[i].max(),"Минимальное:", data[i].min(),
            "Медиана:",data[i].median(),"\nМода:", data[i].mode(), "\n")

PAGE TOTAL LIKES
 Среднее значение: 123194.176 Максимальное: 139441 Минимальное: 81370 Медиана: 129600.0
Мода: 0    136393
dtype: int64

LIFETIME POST TOTAL REACH
 Среднее значение: 13903.36 Максимальное: 180480 Минимальное: 238 Медиана: 5281.0
Мода: 0       677
1      2232
2      2645
3      2938
4      3322
5      3358
6      3414
7      3528
8      3754
9      5280
10     5290
11     6692
12     9528
13    13544
14    32208
dtype: int64

LIFETIME POST TOTAL IMPRESSIONS
 Среднее значение: 29585.948 Максимальное: 1110282 Минимальное: 570 Медиана: 9051.0
Мода: 0     4372
1     6503
2     7004
3     8533
4     8745
5    12735
dtype: int64

LIFETIME ENGAGED USERS
 Среднее значение: 920.344 Максимальное: 11452 Минимальное: 9 Медиана: 625.5
Мода: 0    537
dtype: int64

LIFETIME POST CONSUMERS
 Среднее значение: 798.772 Максимальное: 11328 Минимальное: 9 Медиана: 551.5
Мода: 0    182
1    298
2    319
3    322
4    335
5    374
6    482
7    503
8    513
9    642
dtype: int64

LIFETIME POST CONSUMPTIONS
 Среднее значение: 1415.13 Максимальное: 19779 Минимальное: 9 Медиана: 851.0
Мода: 0    431
1    513
2    599
3    652
4    719
5    730
6    795
7    889
dtype: int64

LIFETIME POST IMPRESSIONS BY PEOPLE WHO HAVE LIKED YOUR PAGE
 Среднее значение: 16766.376 Максимальное: 1107833 Минимальное: 567 Медиана: 6255.5
Мода: 0    1210
1    1284
2    2541
3    2888
4    3675
5    4911
6    4935
7    5010
8    5732
dtype: int64

LIFETIME POST REACH BY PEOPLE WHO LIKE YOUR PAGE
 Среднее значение: 6585.488 Максимальное: 51456 Минимальное: 236 Медиана: 3417.0
Мода: 0       690
1       704
2      1228
3      1640
4      1674
5      1722
6      2044
7      2124
8      2162
9      2174
10     2388
11     2426
12     2604
13     2616
14     2644
15     2660
16     2704
17     2752
18     2868
19     3114
20     3216
21     3230
22     3298
23     3768
24     5348
25     5372
26     7020
27     7800
28     8032
29     8120
30    20608
dtype: int64

LIFETIME PEOPLE WHO HAVE LIKED YOUR PAGE AND ENGAGED WITH YOUR POST
 Среднее значение: 609.986 Максимальное: 4376 Минимальное: 9 Медиана: 412.0
Мода: 0    403
dtype: int64

COMMENT
 Среднее значение: 7.482 Максимальное: 372 Минимальное: 0 Медиана: 3.0
Мода: 0    0
dtype: int64

LIKE
 Среднее значение: 177.94589178356713 Максимальное: 5172.0 Минимальное: 0.0 Медиана: 101.0
Мода: 0    98
dtype: float64

SHARE
 Среднее значение: 27.266129032258064 Максимальное: 790.0 Минимальное: 0.0 Медиана: 19.0
Мода: 0    13
1    14
dtype: float64

TOTAL INTERACTIONS
 Среднее значение: 212.12 Максимальное: 6334 Минимальное: 0 Медиана: 123.5
Мода: 0     0
1    39
2    75
dtype: int64

#### Теперь я найду те же значения отдельно по типам:

In [48]:
types = set()
for i in data['Type']:
    if i not in types:
        types.add(i)
types

{'Link', 'Photo', 'Status', 'Video'}

In [75]:
for t in types:
    tempdata = data[data['Type'] == t]
    print("Значения для '",t.upper(),"':")
    for i in data.columns:
        if i not in notValid:
            print(i.upper() ,'\n','Среднее значение:',tempdata[i].mean(), "Максимальное:", tempdata[i].max(),
                  "Минимальное:", tempdata[i].min(), "Медиана:",tempdata[i].median(),"\nМода:", tempdata[i].mode(), "\n")

Значения для ' STATUS ':
PAGE TOTAL LIKES
 Среднее значение: 132647.04444444444 Максимальное: 139441 Минимальное: 104070 Медиана: 135713.0
Мода: 0    139441
dtype: int64

LIFETIME POST TOTAL REACH
 Среднее значение: 13078.888888888889 Максимальное: 31136 Минимальное: 3930 Медиана: 11096.0
Мода: Series([], dtype: int64)

LIFETIME POST TOTAL IMPRESSIONS
 Среднее значение: 24244.466666666667 Максимальное: 59964 Минимальное: 7509 Медиана: 20849.0
Мода: Series([], dtype: int64)

LIFETIME ENGAGED USERS
 Среднее значение: 2040.2222222222222 Максимальное: 6164 Минимальное: 128 Медиана: 1701.0
Мода: Series([], dtype: int64)

LIFETIME POST CONSUMERS
 Среднее значение: 1949.5555555555557 Максимальное: 5934 Минимальное: 86 Медиана: 1599.0
Мода: Series([], dtype: int64)

LIFETIME POST CONSUMPTIONS
 Среднее значение: 2838.866666666667 Максимальное: 9237 Минимальное: 112 Медиана: 2201.0
Мода: 0    1692
dtype: int64

LIFETIME POST IMPRESSIONS BY PEOPLE WHO HAVE LIKED YOUR PAGE
 Среднее значение: 18664.266666666666 Максимальное: 37849 Минимальное: 5009 Медиана: 17502.0
Мода: Series([], dtype: int64)

LIFETIME POST REACH BY PEOPLE WHO LIKE YOUR PAGE
 Среднее значение: 9908.577777777778 Максимальное: 21352 Минимальное: 2410 Медиана: 8980.0
Мода: Series([], dtype: int64)

LIFETIME PEOPLE WHO HAVE LIKED YOUR PAGE AND ENGAGED WITH YOUR POST
 Среднее значение: 1719.8444444444444 Максимальное: 4376 Минимальное: 101 Медиана: 1604.0
Мода: Series([], dtype: int64)

COMMENT
 Среднее значение: 8.911111111111111 Максимальное: 60 Минимальное: 0 Медиана: 4.0
Мода: 0    2
1    4
dtype: int64

LIKE
 Среднее значение: 176.7111111111111 Максимальное: 859.0 Минимальное: 13.0 Медиана: 150.0
Мода: 0     86
1     99
2    129
3    227
dtype: float64

SHARE
 Среднее значение: 31.42222222222222 Максимальное: 123.0 Минимальное: 1.0 Медиана: 28.0
Мода: 0     1
1    13
2    18
3    36
dtype: float64

TOTAL INTERACTIONS
 Среднее значение: 217.04444444444445 Максимальное: 1009 Минимальное: 17 Медиана: 186.0
Мода: 0    117
1    121
dtype: int64

Значения для ' VIDEO ':
PAGE TOTAL LIKES
 Среднее значение: 135014.85714285713 Максимальное: 138895 Минимальное: 126424 Медиана: 137893.0
Мода: 0    137893
dtype: int64

LIFETIME POST TOTAL REACH
 Среднее значение: 51205.71428571428 Максимальное: 139008 Минимальное: 13544 Медиана: 30624.0
Мода: Series([], dtype: int64)

LIFETIME POST TOTAL IMPRESSIONS
 Среднее значение: 102622.42857142857 Максимальное: 277100 Минимальное: 30235 Медиана: 56950.0
Мода: Series([], dtype: int64)

LIFETIME ENGAGED USERS
 Среднее значение: 1707.0 Максимальное: 3872 Минимальное: 459 Медиана: 1779.0
Мода: Series([], dtype: int64)

LIFETIME POST CONSUMERS
 Среднее значение: 1584.7142857142858 Максимальное: 3822 Минимальное: 411 Медиана: 1643.0
Мода: Series([], dtype: int64)

LIFETIME POST CONSUMPTIONS
 Среднее значение: 2600.1428571428573 Максимальное: 7327 Минимальное: 539 Медиана: 2331.0
Мода: Series([], dtype: int64)

LIFETIME POST IMPRESSIONS BY PEOPLE WHO HAVE LIKED YOUR PAGE
 Среднее значение: 43149.857142857145 Максимальное: 107502 Минимальное: 21436 Медиана: 30131.0
Мода: Series([], dtype: int64)

LIFETIME POST REACH BY PEOPLE WHO LIKE YOUR PAGE
 Среднее значение: 17386.285714285714 Максимальное: 38720 Минимальное: 9568 Медиана: 14112.0
Мода: Series([], dtype: int64)

LIFETIME PEOPLE WHO HAVE LIKED YOUR PAGE AND ENGAGED WITH YOUR POST
 Среднее значение: 979.4285714285714 Максимальное: 2218 Минимальное: 363 Медиана: 885.0
Мода: Series([], dtype: int64)

COMMENT
 Среднее значение: 12.285714285714286 Максимальное: 23 Минимальное: 2 Медиана: 17.0
Мода: 0     2
1    18
dtype: int64

LIKE
 Среднее значение: 231.42857142857142 Максимальное: 449.0 Минимальное: 65.0 Медиана: 204.0
Мода: Series([], dtype: float64)

SHARE
 Среднее значение: 52.142857142857146 Максимальное: 121.0 Минимальное: 13.0 Медиана: 44.0
Мода: 0    13
dtype: float64

TOTAL INTERACTIONS
 Среднее значение: 295.85714285714283 Максимальное: 550 Минимальное: 81 Медиана: 271.0
Мода: Series([], dtype: int64)

Значения для ' PHOTO ':
PAGE TOTAL LIKES
 Среднее значение: 122354.17136150235 Максимальное: 139441 Минимальное: 81370 Медиана: 128032.0
Мода: 0    124940
dtype: int64

LIFETIME POST TOTAL REACH
 Среднее значение: 13137.81455399061 Максимальное: 180480 Минимальное: 238 Медиана: 4675.0
Мода: 0       677
1      2232
2      2938
3      3322
4      3358
5      3414
6      3528
7      3754
8      5280
9      5290
10     9528
11    32208
dtype: int64

LIFETIME POST TOTAL IMPRESSIONS
 Среднее значение: 28994.49765258216 Максимальное: 1110282 Минимальное: 570 Медиана: 8118.5
Мода: 0     4372
1     6503
2     7004
3     8533
4     8745
5    12735
dtype: int64

LIFETIME ENGAGED USERS
 Среднее значение: 818.9460093896714 Максимальное: 11452 Минимальное: 9 Медиана: 605.5
Мода: 0    537
dtype: int64

LIFETIME POST CONSUMERS
 Среднее значение: 690.4319248826291 Максимальное: 11328 Минимальное: 9 Медиана: 528.5
Мода: 0    298
1    319
2    335
3    374
4    482
5    503
6    513
7    642
dtype: int64

LIFETIME POST CONSUMPTIONS
 Среднее значение: 1299.0258215962442 Максимальное: 19779 Минимальное: 9 Медиана: 827.0
Мода: 0    431
1    513
2    599
3    652
4    719
5    730
6    795
7    889
dtype: int64

LIFETIME POST IMPRESSIONS BY PEOPLE WHO HAVE LIKED YOUR PAGE
 Среднее значение: 16422.483568075117 Максимальное: 1107833 Минимальное: 567 Медиана: 5498.0
Мода: 0    1210
1    1284
2    2541
3    2888
4    3675
5    4911
6    4935
7    5010
8    5732
dtype: int64

LIFETIME POST REACH BY PEOPLE WHO LIKE YOUR PAGE
 Среднее значение: 6059.103286384977 Максимальное: 51456 Минимальное: 236 Медиана: 3110.0
Мода: 0       690
1       704
2      1228
3      1640
4      1674
5      1722
6      2044
7      2124
8      2162
9      2174
10     2388
11     2426
12     2604
13     2616
14     2644
15     2660
16     2704
17     2752
18     2868
19     3114
20     3216
21     3230
22     3298
23     3768
24     5348
25     7800
26    20608
dtype: int64

LIFETIME PEOPLE WHO HAVE LIKED YOUR PAGE AND ENGAGED WITH YOUR POST
 Среднее значение: 507.30516431924883 Максимальное: 3430 Минимальное: 9 Медиана: 403.0
Мода: 0    403
dtype: int64

COMMENT
 Среднее значение: 7.492957746478873 Максимальное: 372 Минимальное: 0 Медиана: 3.0
Мода: 0    0
dtype: int64

LIKE
 Среднее значение: 182.61176470588236 Максимальное: 5172.0 Минимальное: 0.0 Медиана: 100.0
Мода: 0     7
1    79
2    98
dtype: float64

SHARE
 Среднее значение: 27.158767772511847 Максимальное: 790.0 Минимальное: 0.0 Медиана: 19.0
Мода: 0    14
dtype: float64

TOTAL INTERACTIONS
 Среднее значение: 216.57981220657277 Максимальное: 6334 Минимальное: 0 Медиана: 122.0
Мода: 0     0
1    39
dtype: int64

Значения для ' LINK ':
PAGE TOTAL LIKES
 Среднее значение: 116363.18181818182 Максимальное: 138895 Минимальное: 85979 Медиана: 115396.0
Мода: 0    138353
dtype: int64

LIFETIME POST TOTAL REACH
 Среднее значение: 18544.590909090908 Максимальное: 70912 Минимальное: 1536 Медиана: 7422.0
Мода: Series([], dtype: int64)

LIFETIME POST TOTAL IMPRESSIONS
 Среднее значение: 28725.454545454544 Максимальное: 229733 Минимальное: 3094 Медиана: 9773.0
Мода: Series([], dtype: int64)

LIFETIME ENGAGED USERS
 Среднее значение: 342.8181818181818 Максимальное: 1374 Минимальное: 24 Медиана: 244.0
Мода: 0    66
dtype: int64

LIFETIME POST CONSUMERS
 Среднее значение: 292.6818181818182 Максимальное: 1106 Минимальное: 23 Медиана: 205.0
Мода: 0    322
dtype: int64

LIFETIME POST CONSUMPTIONS
 Среднее значение: 374.09090909090907 Максимальное: 1345 Минимальное: 26 Медиана: 290.0
Мода: Series([], dtype: int64)

LIFETIME POST IMPRESSIONS BY PEOPLE WHO HAVE LIKED YOUR PAGE
 Среднее значение: 11148.59090909091 Максимальное: 42338 Минимальное: 2307 Медиана: 9034.5
Мода: Series([], dtype: int64)

LIFETIME POST REACH BY PEOPLE WHO LIKE YOUR PAGE
 Среднее значение: 6544.363636363636 Максимальное: 27232 Минимальное: 1180 Медиана: 5039.0
Мода: Series([], dtype: int64)

LIFETIME PEOPLE WHO HAVE LIKED YOUR PAGE AND ENGAGED WITH YOUR POST
 Среднее значение: 210.54545454545453 Максимальное: 788 Минимальное: 19 Медиана: 161.5
Мода: Series([], dtype: int64)

COMMENT
 Среднее значение: 2.8181818181818183 Максимальное: 15 Минимальное: 0 Медиана: 1.5
Мода: 0    0
dtype: int64

LIKE
 Среднее значение: 73.31818181818181 Максимальное: 379.0 Минимальное: 5.0 Медиана: 37.0
Мода: 0    12
1    32
dtype: float64

SHARE
 Среднее значение: 12.909090909090908 Максимальное: 44.0 Минимальное: 0.0 Медиана: 10.5
Мода: 0    2
dtype: float64

TOTAL INTERACTIONS
 Среднее значение: 89.04545454545455 Максимальное: 420 Минимальное: 6 Медиана: 52.5
Мода: 0    14
dtype: int64

### Самый популярный обьект в выборке.

Для определения самого популярного обьекта в выборке нужно посчитать коэфициент популярности, который состоит из суммы некатегориальных признаков с определенными весами. Вопрос в том, какие веса подобрать для признаков. Для начала попробуем дать всем признакам одинаковые веса.

In [139]:
import operator
data1 = data.drop(notValid, axis = 1)
data1.fillna(0, inplace = True)
weight = 1/len(data1.columns)
d = {}
for i in range(len(data)):
    pop = 0
    for c in data1.columns:
            pop += weight*int(data1[c][i])
    d[i] = pop
max(d.items(), key=operator.itemgetter(1))[0]

415

Обьект под номером 415 определился как наиболее популярный. Посмотрим на него.

In [137]:
data.iloc[415]

Page total likes                                                        104070
Type                                                                     Photo
Category                                                                     1
Post Month                                                                   3
Post Weekday                                                                 4
Post Hour                                                                    7
Paid                                                                         0
Lifetime Post Total Reach                                                49632
Lifetime Post Total Impressions                                        1110282
Lifetime Engaged Users                                                    1653
Lifetime Post Consumers                                                   1480
Lifetime Post Consumptions                                                2567
Lifetime Post Impressions by people who have liked your Page           1107833
Lifetime Post reach by people who like your Page                         48368
Lifetime People who have liked your Page and engaged with your post       1513
comment                                                                      7
like                                                                       227
share                                                                       15
Total Interactions                                                         249
Name: 415, dtype: object

Действительно, выглядит убедительно.